services:
  back:
    image: ghcr.io/chroma-case/back
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    env_file:
      - .env
    volumes:
      - ./musics:/musics
  db:
    container_name: db
    image: postgres:alpine3.14
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  front:
    image: ghcr.io/chroma-case/front
    ports:
      - "80:80"
    depends_on:
      - "back"
    env_file:
      - .env
