services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      args:
        DATABASE_URL: ${DATABASE_URL}
    privileged: true
    ports:
      - "8080:3000"
    volumes:
      - ./back:/app
    depends_on:
      - "db"
    env_file:
      - .env
    environment:
    - DATABASE_URL=${DATABASE_URL}
    
  db:
    container_name: db
    image: postgres:alpine3.14
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"