name: Feature Request
description: Request a new feature
labels: [feature]
body:
  - type: markdown
    attributes:
      value: Écrire tout en francais
  - type: input
    attributes:
      label: "En tant que"
      description: "personne qui fait l'action"
    validations:
      required: true
  - type: input
    attributes:
      label: "Je veux"
      description: "description de la feature en une phrase"
    validations:
      required: true
  - type: input
    attributes:
      label: "Estimation du temps"
      placeholder: "3 jours ouvrés (3J/H)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "La description de la feature"
  - type: textarea
    attributes:
      label: "Definition of Done (DoD)"
      description: "Liste de ticks"

