{
 "title": "Chromacase dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "userId", "query": "2" },
   { "name": "username", "query": "lou" },
   { "name": "game_uuid", "label": "game uuid" }
  ]
 },
 "panels": [
  {
   "title": "Back logs by user id",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"chromacase-back-1\"} | json | userId = `$userId`"
    }
   ]
  },
  {
   "title": "Back logs by username",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"chromacase-back-1\"} | json | username = `$username`"
    }
   ]
  },
  {
   "title": "Back logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"chromacase-back-1\"}"
    }
   ]
  },
  {
   "title": "Front logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"chromacase-front-1\"} | json"
    }
   ]
  },
  {
   "title": "Scorometer logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"chromacase-scorometer-1\"}"
    }
   ]
  }
 ]
}