version: "3.4"

services:
  my-nginx-service:
    image: nginx
    container_name: my-nginx-service
    ports:
      - 8000:80
    environment:
      - FOO=bar
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development

  grafana:
    image: grafana/grafana:7.2.2
    container_name: grafana
    volumes:
    - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
    - "3000:3000"

  loki:
   image: grafana/loki:2.8.2
   container_name: loki
   volumes:
     - ./loki.yaml:/etc/config/loki.yaml
   entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml
   ports:
     - "3100:3100"

  logger-app:
    image: mingrammer/flog
    container_name: logger
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development
