FROM python:3.10
RUN wget -q -O /tmp/websocketd.zip \
    https://github.com/joewalnes/websocketd/releases/download/v0.4.1/websocketd-0.4.1-linux_amd64.zip \
    && unzip /tmp/websocketd.zip -d /tmp/websocketd && mv /tmp/websocketd/websocketd /usr/bin \
    && chmod +x /usr/bin/websocketd

WORKDIR /app

COPY ./requirements.txt .
RUN pip install -r ./requirements.txt

CMD /usr/bin/websocketd --port=6543 --devconsole -- python3 ./main.py
