FROM ubuntu:22.04 as buildandroid

# Install dependencies (yarn, nodejs, git, etc.)
RUN apt-get update && apt-get install -y \
    curl \
    git \
    gnupg \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -

RUN npm install -g expo-cli
RUN eas login --non-interactive --username $EAS_USERNAME --password $EAS_PASSWORD
RUN eas:configure -p android