name: "Back skip"
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "back/**"
      - "scorometer/**"
      - '.github/workflows/**'

jobs:
  back_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Success
      run: |
        exit 0


  back_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

    - name: Success
      run: |
        exit 0
