name: Build_Docker

on:
  workflow_call:

jobs:

  Test_Back:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: Staging

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Copy env file to github secret env file
        run: |
          touch .env
          echo "POSTGRES_USER=user" >> .env
          echo "POSTGRES_PASSWORD=eip" >> .env
          echo "POSTGRES_NAME=chromacase" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "DATABASE_URL=postgresql://user:eip@db:5432/chromacase" >> .env
          echo "JWT_SECRET=wow" >> .env
          echo "POSTGRES_DB=chromacase" >> .env
          echo "API_URL=http://localhost:80/api" >> .env
          echo "SCORO_URL=ws://localhost:6543" >> .env

      - name: Down all volumes
        run: docker-compose down --volumes

      - name: Build the app
        run: docker-compose build

      - name: Start the service
        run: docker-compose up -d

      - name: Perform healthchecks
        run: |
          docker-compose ps -a
          wget --retry-connrefused http://localhost:3000 # /healthcheck

      - name: Docker logs
        if: failure()
        run: docker-compose logs

      - name: Remove .env && stop the service
        run: docker-compose down && rm .env