name: Build_Back

on:
  workflow_call:

jobs:

## Build Back ##

  Build_Back:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./back
    environment: Staging

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t testback .