name: Chromatic

on:
  workflow_call:

jobs:

  Chromatic:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: front/
        run: yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: front/
