# name: Build

# on:
#   push:
#     branches:
#       - 'main'
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   build_front:
#   name: Run tests in docker
#   runs-on: ubuntu-latest
#   defaults:
#     run:
#       working-directory: ./front/
#   steps:
#     -name: checkout the repo
#       uses: actions/checkout@v3
#     runs:
# action.yml
# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:
#   using: 'docker'
#   image: 'Dockerfile.test'

name: ci-front

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
