name: "Front skip"

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "front/**"


jobs:

  front_check:
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: |
        exit 0
    
  front_build:
    runs-on: ubuntu-latest
    needs: [ front_check ]
    steps:
    - name: Success
      run: |
        exit 0