name: "Scoro skip"
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "scorometer/**"

jobs:
  scoro_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

    - name: Success
      run: |
        exit 0
