name: Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
 run_front_unit_tests:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./front
  steps:
    - uses: actions/checkout@v3
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install Jest
      run: yarn global add jest
    - name: Install dependencies
      run: yarn install
    - name: Run Unit tests
      run: yarn test